name: sou_estudante
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase e Autenticação
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1

  # Banco de Dados e Armazenamento
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

  # Anúncios
  google_mobile_ads: ^5.1.0

  # Utilitários
  any_link_preview: ^3.0.3
  url_launcher: ^6.3.0
  share_plus: ^9.0.0

  # Para o tema
  shared_preferences: ^2.2.3
  provider: ^6.1.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

# >>> ADICIONE ESTE BLOCO ABAIXO, NO MESMO NÍVEL DE "name:", "environment:", etc. <<<
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png" # Usado para ícones legados e outras plataformas (web, windows, linux)

  # NOVO: Configurações para Ícones Adaptativos no Android
  adaptive_icon_background: "#4A148C" # Cor de fundo (DeepPurple da sua AppColors)
  adaptive_icon_foreground: "assets/app_icon.png" # Sua imagem principal será o primeiro plano

  remove_alpha_ios: true # Recomendado para App Store

  # Configuração para Web
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#4A148C" # Para o web também, use a mesma cor de fundo
    theme_color: "#4A148C"      # E a cor do tema

  # Configuração para Windows e Linux
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  linux:
    generate: true
    image_path: "assets/app_icon.png"